"""change primary key

Revision ID: 725b44e37cf4
Revises: cb33321defc4
Create Date: 2026-01-13 21:53:15.531846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '725b44e37cf4'
down_revision = 'cb33321defc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_info', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('ip',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_info', schema=None) as batch_op:
        batch_op.alter_column('ip',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
