"""initial

Revision ID: 83120b04ba43
Revises: 
Create Date: 2026-01-13 04:34:13.061322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83120b04ba43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_info',
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitor_info')
    # ### end Alembic commands ###
