"""add timestamp

Revision ID: cb33321defc4
Revises: 83120b04ba43
Create Date: 2026-01-13 21:48:30.200584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb33321defc4'
down_revision = '83120b04ba43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_info', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
